universe = vanilla
request_memory = 32768
executable = /home/marcus.lower/public_html/projects/emceeSURF/GWInference/bash_workaround.sh
arguments = $(jobNumber)
getenv = True
accounting_group_user = marcus.lower
accounting_group = ligo.sim.o2.cbc.explore.test
log = /home/marcus.lower/public_html/projects/emceeSURF/GWInference/logs/condor.log
error = /home/marcus.lower/public_html/projects/emceeSURF/GWInference/logs/condor_$(jobNumber).err
output = /home/marcus.lower/public_html/projects/emceeSURF/GWInference/logs/condor_$(jobNumber).out
notification = error
queue 1